# Load your data

In [1]:
import pandas as pd
BRFSS2023_df = pd.read_csv(r"C:\Users\alin2\Downloads\BRFSS2023.csv")

# Get to know its structure

In [2]:
BRFSS2023_df.head()

,_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,_psu,ctelenm1,...,drocdy4_,_rfbing6,_drnkwk2,_rfdrhv8,_flshot7,_pneumo3,_aidtst4,_rfseat2,_rfseat3,_drnkdrv
0,1,1,3012023,3,1,2023,1100,2023000001,2023000001,1.0,...,0,1,0,1,2.0,2.0,2.0,1,1,9
1,1,1,1062023,1,6,2023,1100,2023000002,2023000002,1.0,...,0,1,0,1,1.0,1.0,2.0,1,1,9
2,1,1,3082023,3,8,2023,1100,2023000003,2023000003,1.0,...,0,1,0,1,1.0,1.0,2.0,1,1,9
3,1,1,3062023,3,6,2023,1100,2023000004,2023000004,1.0,...,0,1,0,1,1.0,1.0,1.0,1,1,9
4,1,1,1062023,1,6,2023,1100,2023000005,2023000005,1.0,...,7,1,47,1,2.0,1.0,2.0,1,1,2

In [3]:
BRFSS2023_df.tail()

,_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,_psu,ctelenm1,...,drocdy4_,_rfbing6,_drnkwk2,_rfdrhv8,_flshot7,_pneumo3,_aidtst4,_rfseat2,_rfseat3,_drnkdrv
433318,78,12,12112023,12,11,2023,1100,2023002064,2023002064,NaN,...,71,2,1500,2,2.0,2.0,1.0,1,2,2
433319,78,12,1032024,1,3,2024,1100,2023002065,2023002065,NaN,...,0,1,0,1,NaN,NaN,1.0,1,1,9
433320,78,12,12132023,12,13,2023,1100,2023002066,2023002066,NaN,...,3,1,47,1,NaN,NaN,1.0,1,1,2
433321,78,12,12082023,12,8,2023,1100,2023002067,2023002067,NaN,...,0,1,0,1,2.0,2.0,2.0,1,1,9
433322,78,12,12112023,12,11,2023,1100,2023002068,2023002068,NaN,...,67,2,933,1,NaN,NaN,2.0,1,2,2

In [4]:

BRFSS2023_df.shape

(433323, 350)

In [5]:
BRFSS2023_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Columns: 350 entries, _state to _drnkdrv
dtypes: float64(294), int64(56)
memory usage: 1.1 GB

# Explore individual columns

In [6]:
BRFSS2023_df['seqno'].value_counts(dropna=False)

seqno
2023000032    52
2023000001    52
2023000002    52
2023000003    52
2023000004    52
              ..
2023026392     1
2023026393     1
2023026394     1
2023026395     1
2023026412     1
Name: count, Length: 26444, dtype: int64

In [7]:
BRFSS2023_df

,_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,_psu,ctelenm1,...,drocdy4_,_rfbing6,_drnkwk2,_rfdrhv8,_flshot7,_pneumo3,_aidtst4,_rfseat2,_rfseat3,_drnkdrv
0,1,1,3012023,3,1,2023,1100,2023000001,2023000001,1.0,...,0,1,0,1,2.0,2.0,2.0,1,1,9
1,1,1,1062023,1,6,2023,1100,2023000002,2023000002,1.0,...,0,1,0,1,1.0,1.0,2.0,1,1,9
2,1,1,3082023,3,8,2023,1100,2023000003,2023000003,1.0,...,0,1,0,1,1.0,1.0,2.0,1,1,9
3,1,1,3062023,3,6,2023,1100,2023000004,2023000004,1.0,...,0,1,0,1,1.0,1.0,1.0,1,1,9
4,1,1,1062023,1,6,2023,1100,2023000005,2023000005,1.0,...,7,1,47,1,2.0,1.0,2.0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433318,78,12,12112023,12,11,2023,1100,2023002064,2023002064,NaN,...,71,2,1500,2,2.0,2.0,1.0,1,2,2
433319,78,12,1032024,1,3,2024,1100,2023002065,2023002065,NaN,...,0,1,0,1,NaN,NaN,1.0,1,1,9
433320,78,12,12132023,12,13,2023,1100,2023002066,2023002066,NaN,...,3,1,47,1,NaN,NaN,1.0,1,1,2
433321,78,12,12082023,12,8,2023,1100,2023002067,2023002067,NaN,...,0,1,0,1,2.0,2.0,2.0,1,1,9
433322,78,12,12112023,12,11,2023,1100,2023002068,2023002068,NaN,...,67,2,933,1,NaN,NaN,2.0,1,2,2

In [8]:
BRFSS2023_df.describe()

,_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,_psu,ctelenm1,...,drocdy4_,_rfbing6,_drnkwk2,_rfdrhv8,_flshot7,_pneumo3,_aidtst4,_rfseat2,_rfseat3,_drnkdrv
count,433323.000000,433323.000000,4.333230e+05,433323.000000,433323.000000,433323.000000,433323.000000,4.333230e+05,4.333230e+05,88345.0,...,433323.000000,433323.000000,433323.000000,433323.000000,170823.000000,170823.000000,403710.000000,433323.000000,433323.000000,433323.000000
mean,30.486898,6.612273,6.809769e+06,6.652947,15.479848,2023.058411,1117.783963,2.023005e+09,2.023005e+09,1.0,...,77.469760,1.739282,7826.638676,1.660750,2.138272,2.270057,2.028681,1.633470,1.698735,5.565327
std,16.670560,3.518848,3.429094e+06,3.428158,8.671355,0.234520,38.237812,4.455869e+03,4.455869e+03,0.0,...,225.612523,2.123753,26371.148838,2.113355,2.368834,2.618224,1.686731,2.074538,2.069306,3.515690
min,1.000000,1.000000,1.012024e+06,1.000000,1.000000,2023.000000,1100.000000,2.023000e+09,2.023000e+09,1.0,...,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,18.000000,3.000000,4.042023e+06,4.000000,8.000000,2023.000000,1100.000000,2.023002e+09,2.023002e+09,1.0,...,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,29.000000,7.000000,7.072023e+06,7.000000,15.000000,2023.000000,1100.000000,2.023004e+09,2.023004e+09,1.0,...,3.000000,1.000000,47.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,9.000000
75%,45.000000,10.000000,1.006202e+07,10.000000,23.000000,2023.000000,1100.000000,2.023008e+09,2.023008e+09,1.0,...,29.000000,1.000000,400.000000,1.000000,2.000000,2.000000,2.000000,1.000000,1.000000,9.000000
max,78.000000,12.000000,1.231202e+07,12.000000,31.000000,2024.000000,1200.000000,2.023026e+09,2.023026e+09,1.0,...,900.000000,9.000000,99900.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

In [9]:
BRFSS2023_df.isnull().sum()*100/len(BRFSS2023_df)

_state       0.000000
fmonth       0.000000
idate        0.000000
imonth       0.000000
iday         0.000000
              ...
_pneumo3    60.578368
_aidtst4     6.833932
_rfseat2     0.000000
_rfseat3     0.000000
_drnkdrv     0.000000
Length: 350, dtype: float64

In [10]:
# Filter rows
BRFSS2023_df.loc[BRFSS2023_df['_drnkdrv'] == 1]

,_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,_psu,ctelenm1,...,drocdy4_,_rfbing6,_drnkwk2,_rfdrhv8,_flshot7,_pneumo3,_aidtst4,_rfseat2,_rfseat3,_drnkdrv
517,1,9,9112023,9,11,2023,1100,2023000518,2023000518,1.0,...,17,2,233,1,2.0,1.0,2.0,1,1,1
767,1,11,11152023,11,15,2023,1100,2023000768,2023000768,1.0,...,71,2,2500,2,1.0,1.0,2.0,1,1,1
973,1,1,1222023,1,22,2023,1100,2023000974,2023000974,NaN,...,83,2,5833,2,NaN,NaN,1.0,2,2,1
984,1,1,1192023,1,19,2023,1100,2023000985,2023000985,NaN,...,100,2,3500,2,NaN,NaN,2.0,1,1,1
986,1,1,1112023,1,11,2023,1100,2023000987,2023000987,NaN,...,67,2,933,1,1.0,1.0,2.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433126,78,12,12072023,12,7,2023,1100,2023001872,2023001872,NaN,...,100,2,12600,2,NaN,NaN,1.0,1,1,1
433163,78,12,1022024,1,2,2024,1100,2023001909,2023001909,NaN,...,100,1,2100,2,NaN,NaN,1.0,1,1,1
433170,78,12,12112023,12,11,2023,1100,2023001916,2023001916,NaN,...,86,2,2400,2,1.0,2.0,2.0,2,2,1
433194,78,12,1032024,1,3,2024,1100,2023001940,2023001940,NaN,...,83,1,1167,1,NaN,NaN,1.0,1,1,1
433271,78,12,12142023,12,14,2023,1100,2023002017,2023002017,NaN,...,29,1,600,1,NaN,NaN,1.0,1,1,1

In [11]:
# Sort data 
BRFSS2023_df.sort_values(by='_drnkwk2', ascending=False)

,_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,_psu,ctelenm1,...,drocdy4_,_rfbing6,_drnkwk2,_rfdrhv8,_flshot7,_pneumo3,_aidtst4,_rfseat2,_rfseat3,_drnkdrv
433316,78,12,12142023,12,14,2023,1200,2023002062,2023002062,NaN,...,900,9,99900,9,NaN,NaN,NaN,9,9,9
433294,78,12,12132023,12,13,2023,1200,2023002040,2023002040,NaN,...,900,9,99900,9,NaN,NaN,NaN,9,9,9
67168,12,4,4292023,4,29,2023,1100,2023002354,2023002354,1.0,...,900,9,99900,9,1.0,2.0,2.0,1,1,2
381245,53,8,8292023,8,29,2023,1200,2023000264,2023000264,NaN,...,14,9,99900,9,NaN,NaN,NaN,9,9,9
67187,12,5,5272023,5,27,2023,1200,2023002373,2023002373,1.0,...,900,9,99900,9,NaN,NaN,NaN,9,9,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433312,78,12,12122023,12,12,2023,1100,2023002058,2023002058,NaN,...,0,1,0,1,NaN,NaN,1.0,1,1,9
433311,78,12,1042024,1,4,2024,1100,2023002057,2023002057,NaN,...,0,1,0,1,1.0,1.0,1.0,1,1,9
433307,78,12,12132023,12,13,2023,1100,2023002053,2023002053,NaN,...,0,1,0,1,2.0,2.0,2.0,1,1,9
433305,78,12,12122023,12,12,2023,1100,2023002051,2023002051,NaN,...,0,1,0,1,NaN,NaN,2.0,1,1,9
433303,78,12,12122023,12,12,2023,1100,2023002049,2023002049,NaN,...,0,1,0,1,1.0,9.0,9.0,1,1,9

In [12]:
# Rename or drop columns
BRFSS2023_df = BRFSS2023_df.rename(columns={'_drnkwk2':'drinks_per_week'})
BRFSS2023_df = BRFSS2023_df.drop(columns=['seqno'])

In [13]:
BRFSS2023_df

,_state,fmonth,idate,imonth,iday,iyear,dispcode,_psu,ctelenm1,pvtresd1,...,drocdy4_,_rfbing6,drinks_per_week,_rfdrhv8,_flshot7,_pneumo3,_aidtst4,_rfseat2,_rfseat3,_drnkdrv
0,1,1,3012023,3,1,2023,1100,2023000001,1.0,1.0,...,0,1,0,1,2.0,2.0,2.0,1,1,9
1,1,1,1062023,1,6,2023,1100,2023000002,1.0,1.0,...,0,1,0,1,1.0,1.0,2.0,1,1,9
2,1,1,3082023,3,8,2023,1100,2023000003,1.0,1.0,...,0,1,0,1,1.0,1.0,2.0,1,1,9
3,1,1,3062023,3,6,2023,1100,2023000004,1.0,1.0,...,0,1,0,1,1.0,1.0,1.0,1,1,9
4,1,1,1062023,1,6,2023,1100,2023000005,1.0,1.0,...,7,1,47,1,2.0,1.0,2.0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433318,78,12,12112023,12,11,2023,1100,2023002064,NaN,NaN,...,71,2,1500,2,2.0,2.0,1.0,1,2,2
433319,78,12,1032024,1,3,2024,1100,2023002065,NaN,NaN,...,0,1,0,1,NaN,NaN,1.0,1,1,9
433320,78,12,12132023,12,13,2023,1100,2023002066,NaN,NaN,...,3,1,47,1,NaN,NaN,1.0,1,1,2
433321,78,12,12082023,12,8,2023,1100,2023002067,NaN,NaN,...,0,1,0,1,2.0,2.0,2.0,1,1,9
433322,78,12,12112023,12,11,2023,1100,2023002068,NaN,NaN,...,67,2,933,1,NaN,NaN,2.0,1,2,2

In [14]:
# Check and fix data types if necessary 
BRFSS2023_df['drinks_per_week'] = BRFSS2023_df['drinks_per_week'].astype('float')

In [15]:
# identify missing values
BRFSS2023_df.isna().sum()

_state           0
fmonth           0
idate            0
imonth           0
iday             0
             ...
_pneumo3    262500
_aidtst4     29613
_rfseat2         0
_rfseat3         0
_drnkdrv         0
Length: 349, dtype: int64

In [16]:
# check for duplicate rows 
BRFSS2023_df.duplicated().sum()
BRFSS2023_df = BRFSS2023_df.drop_duplicates()